import { NextAuthProvider } from './providers';
import { ReactNode } from 'react';
import {
    HomeButton,
    LoginButton,
    LogoutButton,
    ProfileButton,
    RegisterButton,
} from '../components/Buttons';

export const metadata = {
    title: 'Welcome to rae-chat-users',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <nav
                    style={{
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center',
                    }}
                >
                    <HomeButton />
                    <RegisterButton />
                    <ProfileButton />
                    <LoginButton />
                    <LogoutButton />
                </nav>
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    );
}
