import { NextAuthProvider } from './providers';
import { ReactNode } from 'react';

export const metadata = {
    title: 'Welcome to rae-chat-users',
    description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <NextAuthProvider>{children}</NextAuthProvider>
            </body>
        </html>
    );
}
